sonar.projectKey=gautamkrishnar_TabPilot
sonar.organization=gautamkrishnar
sonar.host.url=https://sonarcloud.io

sonar.sources=apps/api/src,apps/web/src,packages/shared/src
sonar.tests=apps/api/src,apps/web/src,packages/e2e/tests
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.spec.tsx,**/*.test.tsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/*.d.ts

sonar.javascript.lcov.reportPaths=apps/api/coverage/lcov.info,apps/web/coverage/lcov.info
