import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Auto-generated sidebar from the docs folder structure.
 * Each folder becomes a category; each .md file becomes a doc.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
